### ISSUE TITLE
This is great, just wondering how this might work with sub-collections in Firestore?

### ISSUE THREAD

**Issue by R0M3** [joaqcid/employees-admin#12]
I may be missing something but as far as i can tell this only really works for top level collections? I for example have a comments sub-collection nested in a post document. So my comment service that extends the core Firestore service would need different `basePath`s

**Comment by R0M3** [comment]
Also i guess not ideal for when you don't use firestore to stream data but more like a normal db?

**Comment by joaqcid** [comment]
hi @R0M3! thanks!

you could call a subcollection adding a new method to `FirestoreService`

would be something like this

```
subCollection$(path: string, queryFn?: QueryFn): Observable<T[]> {
        return this.firestore.collection<T>(`${this.basePath}/${path}`, queryFn).valueChanges().pipe(
            tap(r => {
                if (!environment.production) {
                    console.groupCollapsed(`Firestore Streaming [${this.basePath}] [collection$]`)
                    console.table(r)
                    console.groupEnd()
                }
            }),
        );
    }

```

**Comment by joaqcid** [comment]
> Also i guess not ideal for when you don't use firestore to stream data but more like a normal db?

you could write a similar wrapper for the db you connect to, in this case, it's implemented for @angular/fire, so implementation for another service might look different

**Comment by R0M3** [comment]
I do use it for firestore but i just use firestore to get data once... So i think i'm going to add take(1) to all the firestore methods and update the store service a bit to work without the streaming of data... thanks for the help!

**Comment by R0M3** [comment]
Sorry one more thing, i found i had to add the injectable decorator and provide in root to get the core firestore service working, otherwise it was undefined

**Comment by joaqcid** [comment]
right, that is needed when using ivy and angular 9
